### ISSUE TITLE
Support default `in` operation in filters

### ISSUE THREAD

**Issue by neomerx** [limoncello-php/json-api#11]
In order to support such request as

```
GET /comments?filter[post]=1 HTTP/1.1
GET /comments?filter[post]=1,2 HTTP/1.1
GET /comments?filter[post]=1,2&filter[author]=12 HTTP/1.1
```

**Comment by mphasize** [comment]
And important for Ember Data JSONAPIAdapter
`GET /comments?filter[id]=1,2,3,8,9,10`

**Comment by neomerx** [comment]
Syntax `GET /comments?filter[name]=` is also supported which means `name` should be `null`
