### ISSUE TITLE
Add support for `has` filter in relationship

### ISSUE THREAD

**Issue by neomerx** [limoncello-php/json-api#8]
For example, for workspace posts allow user to filter only posts which have files

Something like `/posts?filter[has][files]` or `/posts?filter[files][not-empty] or /posts?filter[files][not]=null`

**Comment by mphasize** [comment]
It should also be possible to combine `has` with `or`, for example:
`/posts?filter[or][has][files]&filter[or][has][links]`

**Comment by neomerx** [comment]
@mphasize I've been playing with it today for some time (yeah, can you believe that? :smile: ) and it becomes over complicated. I guess having trigger that updates `posts.files_number` would be a better solution. In this case it would be even more flexible and such operations as >, <, between and etc could be applied to this value.

**Comment by neomerx** [comment]
For query for `/posts?filter[has][files]` SQL could be
```sql
SELECT posts.* FROM posts, posts_media_files WHERE posts.id_post = posts_media_files.id_post
```


After careful look it appears you can use 'not-null' for relationships with the same effect.

For `belongsTo` it will produce
```sql
SELECT `posts`.*
FROM posts 
WHERE `posts`.`id_board` IS NOT NULL
```
`WHERE` clause is excessive for 'has' usage but it doesn't have any negative effect.

for `hasMany`
```sql
SELECT `boards`.*
FROM boards
INNER JOIN posts posts1 ON `boards`.`id_board`=`posts1`.`id_board`
WHERE `posts1`.`id_post` IS NOT NULL
GROUP BY `boards`.`id_board`
```
`GROUP BY` here is an equivalent for `SELECT DISTINCT`

and for `belongsToMany`
```sql
SELECT `comments`.*
FROM comments
INNER JOIN comments_emotions comments_emotions1 ON
`comments`.`id_comment`=`comments_emotions1`.`id_comment`
WHERE `comments_emotions1`.`id_emotion` IS NOT NULL
GROUP BY `comments`.`id_comment`
```
